version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/pre_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 300
      runas: ubuntu